'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for StackAndConquer
.\"
.\" Copyright (C), 2018, Thorsten Roth
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the man
.\" distribution.
.\"
.\" Mon Jan  01 20:15:00 CEST 2018  ElThoro <elthoro@gmx.de>
.\"
.TH STACKANDCONQUER 6 "2019-08-31" "Thorsten Roth" "StackAndConquer Manual"
.SH NAME
StackAndConquer \- Tower conquest board game
.SH SYNOPSIS
\fBstackandconquer\fP [\fIOption\fP] or/and [\fIFile/Folder\fP]
.SH DESCRIPTION
StackAndConquer is a challenging tower conquest board game.
.SH Options
.TP
\fB\-\-debug\fP
Start debug mode.
.TP
\fB\-\-genboard\fP
Convert *.in file into *.stackboard game board file.
.TP
\fBFile/Folder\fP
Load save game (.stacksav) or if option \-\-genboard is used together with
input file/folder and optional output folder generate a board file.
.SH FILES
.TP
.I /usr/share/stackandconquer/cpu
CPU scripts
.TP
.I /usr/share/stackandconquer/boards
Game boards
.SH BUGS
GitHub bug tracker:

https://github.com/ElTh0r0/stackandconquer/issues
