'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for StackAndConquer
.\"
.\" Copyright (C), 2018, Thorsten Roth
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the man
.\" distribution.
.\"
.\" Mon Jan  01 20:15:00 CEST 2018  ElThoro <elthoro@gmx.de>
.\"
.TH STACKANDCONQUER 6 "2018-01-01" "Thorsten Roth" "StackAndConquer Manual"
.SH NAME
StackAndConquer \- Tower conquest board game
.SH SYNOPSIS
\fBstackandconquer\fP [\fI\-v, \-\-version\fP] oder [\fIFile\fP]
.SH DESCRIPTION
\fPstackandconquer\fP is a challenging tower conquest board game.
.SS Options
.TP
\fB\-v, \-\-version\fP
Print out version.
.TP
\fBFile\fP
Load CPU script (.js) or save game (.stacksav).
.SH DATEIEN
.TP
.I /usr/share/stackandconquer/cpu
CPU scripts
.SH BUGS
GitHub bug tracker:

https://github.com/ElTh0r0/stackandconquer/issues
