version: '0.11.0-{build}'

branches:
  only:
  - main

skip_non_tags: true

environment:
  matrix:
    - BUILD: mingw64_Qt6
      QTDIR: C:\Qt\6.8\mingw_64
      MINGW_DIR: C:\Qt\Tools\mingw1310_64
      PRO_MAKE: mingw32-make
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - BUILD: msvc2022_64
      QTDIR: C:\Qt\6.8\msvc2022_64
      PRO_MAKE: nmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
  
install:
  - set PATH=%QTDIR%\bin;%MINGW_DIR%\bin;%PATH%
  - if %BUILD%==msvc2022_64 call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64

configuration: Release

before_build:
  - qmake stackandconquer.pro
  - lrelease stackandconquer.pro

build_script:
  - '%PRO_MAKE%'

after_build:
  - mkdir StackAndConquer\cpu
  - mkdir StackAndConquer\boards
  - copy release\StackAndConquer.exe StackAndConquer\StackAndConquer.exe
  - windeployqt --release --no-translations --no-opengl-sw StackAndConquer\StackAndConquer.exe
  - copy COPYING StackAndConquer\
  - curl -fsSL -o ReadMe.txt https://raw.githubusercontent.com/ElTh0r0/stackandconquer/packaging/Windows/ReadMe.txt
  - copy ReadMe.txt StackAndConquer\
  - xcopy /i /e /s data\cpu\*.js StackAndConquer\cpu\
  - xcopy /i /e /s data\boards\* StackAndConquer\boards\
  - 7z a StackAndConquer-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip .\StackAndConquer\
  - curl -fsSL -o stackandconquer.nsi https://raw.githubusercontent.com/ElTh0r0/stackandconquer/packaging/Windows/stackandconquer.nsi
  - curl -fsSL -o removeprevious.nsh https://raw.githubusercontent.com/ElTh0r0/stackandconquer/packaging/Windows/removeprevious.nsh
  - curl -fsSL -o stackandconquer.ico https://raw.githubusercontent.com/ElTh0r0/stackandconquer/packaging/Windows/stackandconquer.ico
  - makensis stackandconquer.nsi
  - ren StackAndConquer_Installer.exe StackAndConquer-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.exe

artifacts:
  - path: StackAndConquer-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip
  - path: StackAndConquer-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.exe
