dist: trusty
sudo: required

git:
  depth: 1

language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8
    - os: linux
      compiler: gcc
      
install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -y qt5-default qttools5-dev-tools qtdeclarative5-dev libqt5svg5-dev ; fi

script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then curl -fsSL "https://github.com/ElTh0r0/stackandconquer/raw/packaging/macOS/build_macOS.sh" > "build_macOS.sh" ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then chmod +x build_macOS.sh ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then TAG_NAME=${TRAVIS_TAG} ./build_macOS.sh ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then qmake -config release ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then make ; fi
