version: '0.9.0-{build}'

environment:
  matrix:
    - BUILD: mingw32 
      QTDIR: C:\Qt\5.12\mingw73_32
      MINGW_DIR: C:\Qt\Tools\mingw730_32
      PRO_MAKE: mingw32-make
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - BUILD: msvc2017_64
      QTDIR: C:\Qt\5.12\msvc2017_64
      PRO_MAKE: nmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - BUILD: mingw32_reactos 
      QTDIR: C:\Qt\5.6\mingw49_32
      MINGW_DIR: C:\Qt\Tools\mingw492_32
      PRO_MAKE: mingw32-make
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  
install:
  - set PATH=%QTDIR%\bin;%MINGW_DIR%\bin;%PATH%
  - if %BUILD%==msvc2017_64 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64

configuration: Release

before_build:
  - qmake stackandconquer.pro
  - lrelease stackandconquer.pro

build_script:
  - '%PRO_MAKE%'

after_build:
  - mkdir StackAndConquer\cpu
  - mkdir StackAndConquer\boards
  - copy release\StackAndConquer.exe StackAndConquer\StackAndConquer.exe
  - windeployqt --release --no-translations --no-angle --no-opengl-sw StackAndConquer\StackAndConquer.exe
  - copy COPYING StackAndConquer\
  - copy README.md StackAndConquer\
  - xcopy /i /e /s data\cpu\* StackAndConquer\cpu\
  - xcopy /i /e /s data\boards\* StackAndConquer\boards\
  - 7z a StackAndConquer-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip .\StackAndConquer\
  - curl -fsSL -o stackandconquer.nsi https://raw.githubusercontent.com/ElTh0r0/stackandconquer/packaging/Windows/stackandconquer.nsi
  - curl -fsSL -o stackandconquer.ico https://raw.githubusercontent.com/ElTh0r0/stackandconquer/packaging/Windows/stackandconquer.ico
  - makensis stackandconquer.nsi
  - ren StackAndConquer_Installer.exe StackAndConquer-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.exe

artifacts:
  - path: StackAndConquer-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.zip
  - path: StackAndConquer-%APPVEYOR_BUILD_VERSION%-Windows_%BUILD%.exe
