'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for StackAndConquer
.\"
.\" Copyright (C), 2016, Thorsten Roth
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the man
.\" distribution.
.\"
.\" Fri Oct  28 16:31:00 CEST 2016  ElThoro <elthoro@gmx.de>
.\"
.TH STACKANDCONQUER 6 "2016-10-28" "Thorsten Roth" "StackAndConquer Handbuchseite"
.SH NAME
StackAndConquer \- Tower Conquest Brettspiel
.SH SYNOPSIS
\fBstackandconquer\fP [\fIOption\fP]
.SH BESCHREIBUNG
\fPstackandconquer\fP ist ein anspruchsvolles Tower Conquest Brettspiel.
.SS Optionen
.TP
\fB\-\-version\fP
Versionsnummer ausgeben.
.SH FEHLER
Launchpad Bugtracker:

https://bugs.launchpad.net/stackandconquer
